name: deploy-site
on: [push]
runs-on: ubuntu-latest
steps:
  - name: Install SSH Key
    uses: shimataro/ssh-key-action@v2
    with:
      key: ${{ secrets.SSH_PRIVATE_KEY }}
  - name: Adding Known Hosts
    run: ssh-keyscan -H ${{ secrets.SSH_HOST }}{% endraw%} >> ~/.ssh/known_hosts
  - name: Deploy with rsync
    run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/vincentbowen/personalProjects/Vincent-Bowen-Website