name: deploy
on:
  push:
    branch: main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: uneccesary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -e "/usr/bin/ssh" -av ./dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/~/vincentbowen.com
#testS